
---

- name: set is_pi flag setup
  set_fact:
    is_pi: "{{ ansible_architecture.startswith('arm') }}"
  tags:
    - always

- import_tasks: apt.yml
  tags:
    - apt

- import_tasks: locale.yml
  tags:
    - locale

- import_tasks: ssh.yml
  tags:
    - ssh

- import_tasks: timezone.yml
  tags:
    - timezone

- import_tasks: hostname.yml
  tags:
    - hostname

- import_tasks: users.yml
  tags:
    - user

- import_tasks: automount-drives.yml
  when: is_pi
  tags:
    - automount-drives
