---

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add user to wheel group
  user:
    name: "{{username}}"
    groups:
      - wheel
    append: yes
    state: present
    createhome: yes
    shell: /bin/bash

- name: Set authorized key for user
  authorized_key:
    user: "{{username}}"
    state: present
    key: "{{github_ssh_key_url}}"
  when: github_ssh_key_url != None

# remove other users explicitly

- name: remove login users apart from "{{ username }}"
  user:
    name: '{{ item }}}'
    state: absent
    remove: yes
    # force: yes
  with_items:
    - pi
    - ubuntu
    - centos
  tags:
    - remove_user
    - never 
