---

- name: provision cloud resources
  hosts: all
  roles:
    - role: common 
      become: true  
      tags: 
        - role-common
    - role: tailscale_setup
      become: true
      tags:
        - role-tailscale_setup
