- include_vars: secrets.yml
  tags:
    - always

- name: install consul 1.9.5 version
  unarchive:
    # Rpi4 is arm64, but my raspbianOS runs on armhf compatible 32bit + high floating capability mode
    src: https://releases.hashicorp.com/consul/1.9.5/consul_1.9.5_linux_{{ 'armhfv6' if is_pi else 'amd64' }}.zip
    dest:  /usr/local/bin/
    remote_src: yes
    mode: '0755'
  become: true


- name: add service 
  template: 
    src: consul.service.j2 
    dest: /etc/systemd/system/consul.service
  notify:
    - reload systemctl
  tags:
    - consul_config

- name: enable service
  service:
    name: consul
    enabled: yes

- name: remove existing config files
  shell: /bin/rm -rf /etc/consul/*.hcl

- name: make data dir
  file:
    path: "{{ item }}"
    state: directory
  with_items:
      - /opt/consul/data
      - /etc/consul
  

- name: add daemon.hcl file 
  template:
    src: daemon.hcl.j2
    dest: /etc/consul/daemon.hcl
  tags: 
      - consul_config
  notify: Restart consul


- name: set CONSUL_ADDR in .bashrc for ease
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    regexp: "^export CONSUL_ADDR"
    backrefs: yes
    line: |
      export CONSUL_ADDR=http://{{ ansible_facts.tailscale0.ipv4.address }}:8500
  tags:
      - bashrc
